# Generated by Django 5.1.3 on 2024-12-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0001_initial'),
        ('taxi_fare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=None, null=True)),
                ('model', models.CharField(default=None, null=True)),
                ('color', models.CharField(default=None, null=True)),
                ('state_number', models.CharField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='tariff',
        ),
        migrations.AddField(
            model_name='driver',
            name='fare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_fare.taxifare'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_auth.car'),
        ),
    ]
