# Generated by Django 5.1.3 on 2024-12-27 06:54

import django.db.models.deletion
import driver_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_auth', '0002_car_remove_driver_rating_remove_driver_tariff_and_more'),
        ('taxi_fare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='fare',
            field=models.ForeignKey(default=driver_auth.models.get_default_fare, on_delete=django.db.models.deletion.DO_NOTHING, to='taxi_fare.taxifare'),
        ),
    ]
