# Generated by Django 5.1.3 on 2024-12-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
